### ISSUE TITLE
Long-tracker translation

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/IceFloeTracker.jl#338]
Lots of code in the original MATLAB script; much may not be needed. 

Need to look at start day and next day.

@danielmwatkins can you add a description of the minimum functionality needed?

**Comment by danielmwatkins** [comment]
Rather than translating MATLAB script, the plan is to work within the Julia code to develop methods for extending the image search to multiple floes. A key first step is the addition of floe labels. 

I think the minimum functionality (which is probably doable on our end) is something like this:

`max_days = (something)`
`max_distance = (max_speed * elapsed_time)`
```
for floe in (image such that floe is not matched):
    for next_image in (images with time < max_days):
       for floes within max_distance:
            look_for_matches(floe, next_image_floes)
```

So in order to do this, we'd need to 
* make sure that the dates of images are available to the floe tracker module, which was enabled by the addition of floe labels
* see how to add parameters to the config file for the search limitations
* make sure that the documentation is clear enough on how the tracker module goes through the set of images so we know where to add the additional functionality

**Comment by cpaniaguam** [comment]
#352

**Comment by danielmwatkins** [comment]
Coming back to this, we do really need a way to extend floe tracking past small gaps from cloud cover and/or from segmentation errors. I'm not sure whether this is best addressed in the Julia package or in the pipeline, though.
