### ISSUE TITLE
supplied notebook returns error

### ISSUE THREAD

**Issue by Thorkage** [WilhelmusLab/IceFloeTracker.jl#452]
Hi!

in the "track-floes.ipynb" notebook the cell which calls the pairfloes function returns an error in the given setup:
This is the call: 
`props, tracked = pairfloes(imgs, props, passtimes, dt, condition_thresholds, mc_thresholds);
`

And this is the error:

```
MethodError: no method matching pairfloes(::Vector{BitMatrix}, ::Vector{DataFrame}, ::Vector{Dates.DateTime}, ::Vector{Float64}, ::Tuple{NamedTuple{(:dt, :dist), Tuple{Tuple{Float64, Float64, Float64}, Tuple{Int64, Int64, Int64}}}, NamedTuple{(:area, :arearatio, :majaxisratio, :minaxisratio, :convexarearatio), Tuple{Int64, Vararg{Float64, 4}}}, NamedTuple{(:area, :arearatio, :majaxisratio, :minaxisratio, :convexarearatio), Tuple{Int64, Vararg{Float64, 4}}}}, ::NamedTuple{(:goodness, :comp), Tuple{NamedTuple{(:area3, :area2, :corr), Tuple{Float64, Float64, Float64}}, NamedTuple{(:mxrot, :sz), Tuple{Int64, Int64}}}})

Closest candidates are:
  pairfloes(::Vector{BitMatrix}, ::Vector{DataFrame}, ::Vector{Dates.DateTime}, ::Any, ::Any)
   @ IceFloeTracker ~/Library/CloudStorage/OneDrive-Personal/UNIS_remoteSensing/project/IceFloeTracker.jl/src/tracker/tracker.jl:47

Stacktrace:
 [1] top-level scope
   @ ~/Library/CloudStorage/OneDrive-Personal/UNIS_remoteSensing/project/IceFloeTracker.jl/notebooks/track-floes/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_X12sZmlsZQ==.jl:2

```

I saw that there are 2 functions (_pairfloes and pairfloes in tracker.jl). The used arguments when calling in the notebook seem more related to the _pairfloes function. So I removed _dt_ as an argument. But when I use this I get another error:

```
AbstractDataFrame is not iterable. Use eachrow(df) to get a row iterator or eachcol(df) to get a column iterator
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] iterate(#unused#::DataFrame)
   @ DataFrames ~/.julia/packages/DataFrames/kcA9R/src/abstractdataframe/iteration.jl:23
 [3] indexed_iterate(I::DataFrame, i::Int64)
   @ Base ./tuple.jl:91
 [4] top-level scope
   @ ~/Library/CloudStorage/OneDrive-Personal/UNIS_remoteSensing/project/IceFloeTracker.jl/notebooks/track-floes/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_X12sZmlsZQ==.jl:2
```

Can you help me to get it running?

**Comment by cpaniaguam** [comment]
@Thorkage thanks for catching this! There were some features introduced to the `pairfloes` function but we failed to update the notebook -- our bad!

The problem is that the `pairfloes` function takes in a path to a reference image to extract lat/lon metadata instead of a vector of "times" `dt`. I already have request to update the public version of the notebook in the `update-track-floes-nb` branch. For the moment you can find the notebook with the updates [here](https://github.com/WilhelmusLab/IceFloeTracker.jl/blob/update-track-floes-nb/notebooks/track-floes/track-floes.ipynb).

Again, thanks for bringing that to our attention. We'll be pushing these changes to the repo soon and ensure the notebooks stay up-to-date with the code base.

Carlos
